### ISSUE TITLE
Error run RealSense D435I

### ISSUE THREAD

**Issue by nikitos1401** [stella-cv/stella_vslam#494]
--Type <RET> for more, q to quit, c to continue without paging--c

Thread 9 "run_slam" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe2ffd700 (LWP 18451)]
0x00007ffff715ba08 in cv::_InputArray::size(int) const () from /usr/local/lib/libopencv_core.so.405
(gdb) bt
#0  0x00007ffff715ba08 in cv::_InputArray::size(int) const () at /usr/local/lib/libopencv_core.so.405
#1  0x00007ffff2a35140 in cv::imshow(cv::String const&, cv::_InputArray const&) ()
    at /usr/local/lib/libopencv_highgui.so.3.4
#2  0x00007ffff67c1d96 in pangolin_viewer::viewer::run() (this=0x7fffffffd290)
    at /usr/local/include/opencv2/core/cvstd.inl.hpp:81
#3  0x000055555559cf76 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<tracking(std::shared_ptr<stella_vslam_ros::system> const&, std::shared_ptr<stella_vslam::config> const&, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)::{lambda()#1}> > >::_M_run() ()
#4  0x00007ffff63b8de4 in  () at /lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff6de1609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#6  0x00007ffff60a5133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
I run command: gdb -ex r --args /home/user/catkin_ws/devel/lib/stella_vslam_ros/run_slam -v ~/stella_vslam/build/orb_vocab.fbow -c ~/stella_vslam/example/euroc/EuRoC_D435i.yaml --map-db-out ~/my_maps/map.msg

**Comment by nikitos1401** [comment]
@ymd-stella Why did you close my question? could you help me solve my problem

**Comment by nikitos1401** [comment]
I'm sorry, I can't deal with the problem, so I turned to you for help, I didn't mean to offend you, thank you!
